= REST API 문서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한 한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 때 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한 한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함

| `204 No Content`
| 기존 리소스를 성공적으로 수정함

| `400 Bad Request`
| 잘못된 요청을 보낸 경우

| `404 Not Found`
| 요청한 리소스가 없음

| `500 Internal Server Error`
| 서버 내부 오류
|===

[[resources]]
= 리소스

[[resources-user]]
== 사용자

[[resources-user-create]]
=== 사용자 생성

`POST` 요청을 사용해서 새로운 사용자를 생성할 수 있습니다.

operation::user-create[snippets='http-request,request-fields,http-response,response-fields']

[[resources-user-get]]
=== 사용자 조회

`GET` 요청을 사용해서 사용자 정보를 조회할 수 있습니다.

operation::user-get[snippets='http-request,path-parameters,http-response,response-fields']

[[resources-user-list]]
=== 사용자 목록 조회

`GET` 요청을 사용해서 사용자 목록을 조회할 수 있습니다.

operation::user-list[snippets='http-request,query-parameters,http-response,response-fields']

[[resources-user-update]]
=== 사용자 수정

`PUT` 요청을 사용해서 기존 사용자 정보를 수정할 수 있습니다.

operation::user-update[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

[[resources-user-delete]]
=== 사용자 삭제

`DELETE` 요청을 사용해서 사용자를 삭제할 수 있습니다.

operation::user-delete[snippets='http-request,path-parameters,http-response']